[package]
name = "ngtq_integration_test"
version = "0.1.0"
edition = "2021"

[dependencies]
ngtq_bus_service_client = { path = "../ngtq_bus_service_client"}
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"