[package]
name = "ngtq_bus_service"
version = "0.1.0"
edition = "2021"

[dependencies]
ngtask_queue = { path = "../ngtask_queue" }
ngtq = { path = "../ngtq" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"