name: Release

on:
  push:
    branches:
      - main

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Get Previous tag
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: v0.0.0

      - name: Generate Next Version
        id: semvers
        uses: "WyriHaximus/github-action-next-semvers@v1"
        with:
          version: ${{ steps.previoustag.outputs.tag }}

      - name: Build Release
        run: cargo build --release --verbose -p ngtq_bus_service
        
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.semvers.outputs.patch }}
          files: |
            target/release/ngtq_bus_service
          body: |
            # NGTQ Bus Service - Initial Release
            
            First release of the Next Generation Task Queue Bus Service implementation.
            
            ## Features
            - Task queue implementation with unique ID support
            - Category-based task management
            - IPC socket communication
            - Linux support
            
            ## Installation
            Download the `ngtq_bus_service` binary and ensure execute permissions:
            ```bash
            chmod +x ngtq_bus_service
            ```
            
            ## Configuration
            Default IPC socket path: `/tmp/resu_ipc_socket`
          draft: false
          prerelease: false